apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mynode
  name: mynode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynode
  template:
    metadata:
      labels:
        app: mynode
    spec:
      containers:
      - name: mynode
        image: quay.io/burrsutter/mynode:v1         
        ports:
          - containerPort: 8000

