apiVersion: v1
kind: Service
metadata: 
  name: postgres
  labels:
    app: postgres
    visualize: "true"
spec: 
  ports:
    # the port that this service should serve on
    - port: 5432  
  selector: 
    app: postgres